name: "Label new pull request"
description: "Add a new label when a new PR is opened"
author: "Rakesh-krishnamoorthy"

inputs:
  gh-token:
    description: 'The github token for authentication'
    required: true
  label:
    description: 'The label to be applied to the pull request'
    required: true

    
runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: 'activity'
  color: 'blue' 
