name: hello

on:
    workflow_dispatch:
    push:
    pull_request:
        types: [opened , reopened]

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: cheskout repository
              uses: action/checkout/v2

            - name: Run action
              uses: ./
              with: 
                gh-token: ${{ secrets.GH_TOKEN }}
                label: 'needs-review'
                