name: hello

on:
    workflow_dispatch:
    pull_request:
        types: [opened , reopened]

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            
            - uses: action/checkout/v2
            
            - uses: ./
              with: 
                gh-token: ${{ secrets.GH_TOKEN }}
                label: 'needs-review'
                